apiVersion: v1
kind: Service
metadata:
  name: ecume-backend
  namespace: ecume
spec:
  type: ClusterIP
  selector:
    app: ecume-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
