apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecume
  namespace: ecume
spec:
  rules:
    - host: ecume.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecume-frontend
                port:
                  name: http
