apiVersion: v1
kind: Secret
metadata:
  name: ecume-secrets
  namespace: ecume
type: Opaque
stringData:
  EXTERNAL_LLM_API_KEY: REPLACE_ME
  ECUME_RDF_AUTH_USERNAME: REPLACE_ME
  ECUME_RDF_AUTH_SECRET: REPLACE_ME
  FUSEKI_USER: REPLACE_ME
  FUSEKI_PASSWORD: REPLACE_ME
  ONTOCAST_TOKEN: REPLACE_ME
